
createApi="YOUR_CLOUD_FUNCTION_TRIGGER_URL"

updateApi="YOUR_CLOUD_FUNCTION_TRIGGER_URL"

deleteApi="YOUR_CLOUD_FUNCTION_TRIGGER_URL"

queryApi="YOUR_CLOUD_FUNCTION_TRIGGER_URL"

listApi="YOUR_CLOUD_FUNCTION_TRIGGER_URL"
